### ISSUE TITLE
Startup

### ISSUE THREAD

**Issue by homuser2003** [mstuettgen/homeassistant-addons#1]
Hi,

this is what I´m looking for since the Home4 is really bad in disclosing information AND the APP sucks.

I believe I have set it up correctly according to the instructions. However when I start it immediately shows:
`Traceback (most recent call last):
  File "/home/pi/homeassistant/senecweb2mqtt/senec_mqtt_device.py", line 226, in <module>
    main()
  File "/home/pi/homeassistant/senecweb2mqtt/senec_mqtt_device.py", line 16, in main
    d = SenecMQTTDevice()
  File "/home/pi/homeassistant/senecweb2mqtt/senec_mqtt_device.py", line 72, in __init__
    self._mqtt_client.connect(self._MQTT_HOST, self._MQTT_PORT)
  File "/home/pi/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 912, in connect
    self.connect_async(host, port, keepalive,
  File "/home/pi/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 979, in connect_async
    if port <= 0:
TypeError: '<=' not supported between instances of 'str' and 'int'
`

Was mach ich falsch?

Thanks

homeuser

**Comment by mstuettgen** [comment]
Hmm das ist ein Fehler der direkt aus der "paho mqtt client" Klasse kommt...
Läuft denn der MQTT Broker in Home Assistant UND die MQTT Integration ?

Auf meine Raspberry Pi, auf dem das Script läuft, ist Python 3.9.2 installiert.

Edit:
Ich glaube ich hab den Fehler gefunden, bitte den Port wie folgt angeben:

```
self._MQTT_PORT = 1883
 ```
und nicht wie in in der Anleitung
```
self._MQTT_PORT = "1883"
 ```

**Comment by homuser2003** [comment]
Läuft!

Sehr cool! Tatsächlich möchte ich das gar nicht in Homeassistant sondern in erster Linie in EVCC und Sekundär in FHEM nutzen...

Dann bastle ich mal weiter! Auf Basis von MQTT auf meinem Broker sollte ich damit eigentlich weiter kommen...

Vielen Dank!

**Comment by Frevven** [comment]
Hallo,

wenn ich den Dienst wie beschrieben auf meine Raspberry starte, erhalte ich folgende Status-Ausgabe :

Sep 01 18:01:21 raspberrypi python3[18070]: DEBUG:senec_webgrabber:***** update(self) ********
Sep 01 18:01:21 raspberrypi python3[18070]: DEBUG:urllib3.connectionpool:https://mein-senec.de:443 "POST /auth/login HTTP/1.1" 302 0
Sep 01 18:01:22 raspberrypi python3[18070]: DEBUG:urllib3.connectionpool:https://mein-senec.de:443 "GET /auth/login?error=1 HTTP/1.1" 200 None
Sep 01 18:01:22 raspberrypi python3[18070]: INFO:senec_webgrabber:Login successful
Sep 01 18:01:22 raspberrypi python3[18070]: DEBUG:senec_webgrabber:***** update(self) ********
Sep 01 18:01:22 raspberrypi python3[18070]: DEBUG:senec_webgrabber:***** update_now_kW_stats(self) ********
Sep 01 18:01:22 raspberrypi python3[18070]: DEBUG:urllib3.connectionpool:https://mein-senec.de:443 "GET /endkunde/api/status/getstatusoverview.php?anlageNummer=0 HTTP/1.1" 302 0
Sep 01 18:01:22 raspberrypi python3[18070]: DEBUG:urllib3.connectionpool:https://mein-senec.de:443 "GET /endkunde/oauth2/authorization/endkunde-portal HTTP/1.1" 302 0
Sep 01 18:01:22 raspberrypi python3[18070]: DEBUG:urllib3.connectionpool:https://mein-senec.de:443 "GET /auth/oauth2/authorize?response_type=code&client_id=endkunde-portal&scope=endkunde&state=Ru6sE3ZyxIU1iAk11FtojeQ71vUFdczp4he-iKbONuY%
Sep 01 18:01:22 raspberrypi python3[18070]: DEBUG:senec_webgrabber:***** update(self) ********

Was mache ich falsch?
