### ISSUE TITLE
Historische Daten der API?

### ISSUE THREAD

**Issue by loeffelpan** [mstuettgen/homeassistant-addons#3]
Hallo,
ich hätte in Zusammenhang mit https://github.com/marq24/ha-senec-v3/discussions/17 eine Frage bzgl. der API-Daten. Die o. g. Integration und auch die Python-Lösung hier sammelt regelmäßig den aktuellen Total-Wert über "getstatus.php" ein.

Nun ist mein Ziel über API-Calls die Daten für vergangene Tage zu rekonstruieren und in die Datenbank von Homeassistant einzufügen.

Jetzt zu meiner Frage:
Gibt es über die API die Möglichkeit den Total-Wert von vergangenen Tage abzufragen?
Mir ist bisher nur gelungen die Tages-Werte zu ermitteln und die vergangenen Total-Werte zu auf Basis eines aktuellen Total-Werts zu errechnen.

**Comment by oakdesign** [comment]
Habe gestern meine Senec V4 in betreib genommen bekommen und stehe vor dem gleichen Probelm. Was ich bisher gefunden habe ist, dass man sich über die Senec App unter Dukomente -> Statisitsche Daten die Messwerte pro KW als csv Datei per Mail schicken lassen kann. Die Messungen sind im Abstand von 1-60sec und enthalten folgende Werte.
Uhrzeit	Netzbezug [kW]	Netzeinspeisung [kW]	Stromverbrauch [kW]	Akkubeladung [kW]	Akkuentnahme [kW]	Stromerzeugung [kW]	Akku Spannung [V]	Akku Stromstärke [A]

**Comment by loeffelpan** [comment]
Die Werte sind für Homeassistant nicht zu gebrauchen. Weil die Zeitspanne immerzu variiert.

Es gibt hier eine Integration, die für V4 Systeme funktioniert. Und für historische Daten habe ich [hier](https://github.com/marq24/ha-senec-v3/issues/11#issue-1884431618) etwas dokumentiert. Ich werde voraussichtlich am WE noch ein Powershell-Skript ergänzen, mit man Tageswerte von der API auslesen und für HA aufbereiten kann.
Würde hier mal zu machen, da die API die angefragten Daten scheinbar nicht liefern kann.

**Comment by loeffelpan** [comment]
@oakdesign
Falls du interessiert bist. Mein Skript ist fertig.
https://gist.github.com/loeffelpan/10bdb7e5bfd21568a9cb05d429aaf214

Fragen/Feedback gerne.

**Comment by oakdesign** [comment]
@loeffelpan danke für den Hinweis. 
Ich hab meine Lösung in Node-Red implementiert und nutze auch nicht mehr die Daten aus mein-senec.de sondern das https://app-gateway-prod.senecops.com, aus der auch die senec-app seine Daten zieht.
1. Gibt es hier nicht das issue mit Session Cookies sondern es einmalig ein Logintoken erstellt der auch dauerhaft gültig ist. 
2. Historische daten lassen sich mit Auflösung Stude,Tag,Monat,Jahr für jeden beliebigen Zeitpunkt holen.
3. Man kann Wallbox Daten lesen und auch setzen

hier eine Übersicht über die Verfügbaren Service Endpoints
https://documenter.getpostman.com/view/10329335/UVCB9ihW#3e5a4286-c7d2-49d1-8856-12bba9fb5c6e

**Comment by loeffelpan** [comment]
Du hast scheinbar nicht reingeschaut - macht aber nichts.
Genau die API nutze ich auch. Allerdings hab ich inzwischen einen v2-Endpunkt genommen. Die Daten bei v1 waren meiner Meinung nach inkonsistent (Jahressumme passte nicht zur Summe aller Tage).

**Comment by oakdesign** [comment]
@loeffelpan Erst reingeschaut nachdem ich schon kommentiert hatte. 
wie bist du den auf den v2 gekommen? der lauft ja auf https://app-gateway.prod.senec.dev im gegensatz dem den ich selbst nutze auf **.com**
allerdings sieht es bei mir anders aus,aus dem
https://app-gateway.prod.senec.dev/v2/senec/systems/{{anlageid}}/measurements?resolution=MONTH&from=1698098400&to=1698271200 bekomme ich keine totals 
auf dem dev gateway läuft aber auch eine v1 und mit der
https://app-gateway.prod.senec.dev/v1/senec/systems/{{anlageid}}/measurements?resolution=MONTH&from=1698098400&to=1698271200 bekomme ich die totals

**Comment by loeffelpan** [comment]
Da mein Skript nicht auf die Totals angewiesen ist, sondern diese selber errechnet, hatte ich auf die Totals nicht geachtet.
Die .dev-URL hab ich aus einem Proxy ausgelesen, als ich meine App genutzt habe.

Ich wusste nicht, dass es den measurements-Endpunkt auch auf der v1 gibt. Der wird nämlich auch bei "getpostman" nicht erwähnt.

Spannend. Muss ich mir nochmal ansehen.
Danke für die Hinweise.

**Comment by oakdesign** [comment]
@loeffelpan hab mir das ganze jetzt mal in genymotion als emulator aufgesetzt und auf einem die aktuelle app v4.3.3 und die neue die mal als google play beta tester bekommt v4.4.0_beta01 , und jetzt ist mir klar wo die beiden gateways herkommen.
app-gateway-prod.senecops.com ist der für die aktuelle stable app, und app-gateway.prod.senec.dev wird von der beta app angesprochen

**Comment by loeffelpan** [comment]
Klingt plausibel.
Allerdings nutzeich iOS und wüsste gerade nicht mal, wie ich an die Beta App kommen würde. Das dev-Gateway muss (unbeabsichtigt) auch mal in einer Final App gewesen sein. Und scheinbar bereiten die dann in der 4.4.0 die v2-API vor. Denke mal da kommen dann auch bald die "Total"-Werte.

Aber werde dann mit meinem Skript auch auf die .com URL gehen. Danke auch für deine Recherche.

**Comment by oakdesign** [comment]
In der Beta sind v1 und v2 gemischt. Ich habe den Traffic aus der Beta komplett über einen proxy mitgetrackt. Zudem greift die App auch noch teilweise auf die oauth Service von mein-senec.de zu
![senecapp](https://github.com/mstuettgen/homeassistant-addons/assets/1496441/fc20d45e-808c-4ebb-8c34-eb90949a5992)
