### ISSUE TITLE
MQTT-Disconnect not handled

### ISSUE THREAD

**Issue by wdill** [mstuettgen/homeassistant-addons#4]
Moin,
erstmal: Script funktioniert grundsätzlich super - Danke für Deine Arbeit!

Einen Verbesserungswunsch habe ich aber: 
Wenn die API bei Senec längere Zeit nicht erreichbar ist, bricht (nach Ablauf von KeepAlive) die Verbindung zum MQTT-Broker ab und wird auch nicht wieder aufgebaut. Das Script läuft aber sauber weiter, nur werden die Daten nicht mehr "gepublisht".

Habe versucht, mich durch den Python-Code zu wurschteln (ohne Ahnung von Python zu haben) und meine, dass man den Resultcode der publish-Aufrufe abfragen könnte (z.B.  >> rc = self._mqtt_client.publish(state_topic, str(round(value,3)) <<), um dann im Fehlerfall die Verbindung neu aufzubauen.

Wie gesagt: Keine Ahnung von Python :-)

Danke für Deine Mühe
Werner

**Comment by mstuettgen** [comment]
Hallo!
Sorry für die späte Antwort, ich war im Urlaub und hatte jetzt erst wieder Zeit mich mal wieder drum zu kümmern. Das Problem mit dem Disconnect war mir bekannt, bisher war meine Lösung das Script per Cronjob einfach automatisch alle 30 Minuten neu zu starten. Ich habe aber gerade eine Update gepushed was das Problem hoffentlich dauerhaft löst. Bitte gerne testen und Feedback geben!

https://github.com/mstuettgen/homeassistant-addons/blob/main/senecweb2mqtt/senec_mqtt_device.py#L75

**Comment by mstuettgen** [comment]
Hallo, ich habe soeben Version 1.0 veröffentlicht. Man kann das Programm jetzt direkt als Addon installieren und das Problem der Disconnects sollte nun auch behoben sein. Daher schließe ich das hier erstmal wieder.
