### ISSUE TITLE
Probleme beim runterladen 

### ISSUE THREAD

**Issue by floball44** [mstuettgen/homeassistant-addons#5]
Hallo! Ich habe versucht das Add-On über die url runterzuladen. Mir wird angezeigt, dass das Herunterladen erfolgreich war das Add-On wird mir nicht im Add-On Store angezeigt. Versuche ich über die URL eine zweite Installation, dann wird angezeigt, dass das Add-On bereits installiert ist. Ich finde meinen Fehler irgendwie nicht... 

Danke für die Hilfe

**Comment by mstuettgen** [comment]
Hallo!

Die Installation als direktes Addon geht leider (noch) nicht, siehe auch hierzu die Readme im eigentlichen "Addon":

https://github.com/mstuettgen/homeassistant-addons/tree/main/senecweb2mqtt

Ich gebe zu, dass das verwirrend sein kann, wenn man auf der Hauptseite der Anleitung folgt, das sollte ich bei Gelegenheit mal ändern.

Kurz gesagt: Die beiden PythonFiles herunterladen, die Benutzer-/Konfigurationsdaten entsprechend der Readme Datei eintragen, und dann das Script von Hand starten.

**Comment by floball44** [comment]
Hi,
Vielen Dank für die schnelle Antwort und die Arbeit, die du dir gemacht hast! Leider bin ich noch ein Anfänger was Home Assistant angeht und weiß leider nicht, wie und wo ich das Skript ausführen muss. Vielen Dank aber für deine schnelle Antwort! 
Schöne Grüße 
 
 
  Am Mi., Apr. 3, 2024 at 19:08 schrieb Marcel ***@***.***>:   


Hallo!

Die Installation als direktes Addon geht leider (noch) nicht, siehe auch hierzu die Readme im eigentlichen "Addon":

https://github.com/mstuettgen/homeassistant-addons/tree/main/senecweb2mqtt

Ich gebe zu, dass das verwirrend sein kann, wenn man auf der Hauptseite der Anleitung folgt, das sollte ich bei Gelegenheit mal ändern.

Kurz gesagt: Die beiden PythonFiles herunterladen, die Benutzer-/Konfigurationsdaten entsprechend der Readme Datei eintragen, und dann das Script von Hand starten.

**Comment by mstuettgen** [comment]
Ok dann hier noch ein paar zusätzliche Infos:
Aus Homeassistant heraus kann man das Skript derzeit **nicht** direkt starten. 

Du musst die beiden Python-Files entweder auf einen Windows oder einen Linux-PC herunterladen. Auf dem PC muss Python3 installiert sein. Wenn die Dateien heruntergeladen sind musst du die Zugangsdaten etc korrekt ausfüllen, das kann man zB mit einem Texteditor machen (siehe README).

Wenn alles korrekt eingetragen ist musst du eine Konsole bzw ein Terminalfenster öffnen, in den Ordner navigieren, in dem die Dateien liegen und dann mit dem Befehl aus der README starten. 

Bei mir läuft das Skript auf einem separaten Raspberry Pi, also getrennt von Home Assistant.

Wenn dir das zu kompliziert ist dann schau dir mal das Repo von Marq24 an, der bietet eine vollständige Integration an:
https://github.com/marq24/ha-senec-v3

**Comment by mstuettgen** [comment]
Hallo, ich habe soeben Version 1.0 veröffentlicht. Man kann das Programm jetzt direkt als Addon installieren und das Problem der Disconnects sollte nun auch behoben sein. Daher schließe ich das hier erstmal wieder.

**Comment by floball44** [comment]
Sehr cool! Vielen lieben Dank! Bei der anderen Lösung hätte ich noch alle Entitäten zu mqtt über eine Automatisierung senden müssen. Das war sehr umständlich. Vielen Dank für die Arbeit! 
 
 
  Am Sa., Apr. 6, 2024 at 19:05 schrieb Marcel ***@***.***>:   


Closed #5 as completed.
